services:
  - type: web
    name: backendvizionacademy
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://backendvizionacademy.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
