version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:replace_with_your_app_key
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: vizionacademy
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret
    depends_on:
      - db
    volumes:
      - .:/var/www

  db:
    image: postgres:15
    container_name: laravel-db
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
